OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "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"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"
